config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' , sessions: 'users/sessions'}

  root to: 'homepages#index'
  resources :homepages
  # devise_for, :users, contollers: {
  # registrations: 'users/registrations', # This controller handles actions related to user sign-up and account management.
  # session: 'users/sessions', # This controller handles actions related to user sign-in and sign-out.
  # omniauth_callbacks: 'users/omniauth_callbacks' # This controller manages the authentication flow when users sign in using external providers like Google, Facebook, etc.
  # }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
    get 'users/verify_two_factor', to: 'users/sessions#verify_two_factor'
    post 'users/verify_two_factor', to: 'users/sessions#verify_two_factor'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :linkedin]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.department = auth.info.department
      user.role = auth.info.role
      user.onboarding_status = auth.onboarding_status
      user.phone_number = auth.info.phone_number
      user.date_of_joining = auth.info.date_of_joining
    end
  end

  def generate_two_factor_code
    self.two_factor_code = rand(100000..999999).to_s
    self.two_factor_expires_at = 10.minutes.from_now
    save!
  end

  def invalidate_two_factor_code
    self.two_factor_code = nil
    self.two_factor_expires_at = nil
    save!
  end

  def verify_two_factor_code(code)
    self.two_factor_code == code && two_factor_expires_at > Time.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  # protect_from_forgery with: :exception
  
  # # Disable CSRF protection for OmniAuth callback route
  # skip_before_action :verify_authenticity_token, only: :omniauth_callback

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number,:department, :role, :date_of_joining, :onboarding_status])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number,:department, :role, :date_of_joining, :onboarding_status])
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  end 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
    user = User.from_omniauth(auth)
    byebug
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise_omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = 
        t 'devise_omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized"
      redirect_to_new_user_session_path
    end
  end
  
  private
  
  def auth
    auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def update_resource(resource, params)
    if google_oauth?(resource)
      params.delete('current_password')
  
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
  
  private
  
  def google_oauth?(user)
    user.provider == 'google_oauth2'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :check_two_factor_auth, only: [:create]

  def check_two_factor_auth
    user = User.find_by(email: params[:user][:email])
    if user && user.valid_password?(params[:user][:password])
      user.generate_two_factor_code
      UserMailer.send_two_factor_code(user).deliver_now
      redirect_to users_verify_two_factor_path(user_id: user.id)
    end
  end

  def verify_two_factor
    @user = User.find(params[:user_id])
    if request.post?
      if @user.verify_two_factor_code(params[:two_factor_code])
        @user.invalidate_two_factor_code
        sign_in(@user)
        redirect_to root_path, notice: 'Successfully logged in with 2FA!'
      else
        flash.now[:alert] = 'Invalid or expired code'
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/homepages/index.html.erb
<% if current_user %>
  <h2> <%= current_user.email%> </h2>
  <%= link_to "Edit Account", edit_user_registration_path %> 
   <%= link_to "Logout", users_sign_out_path, class: 'nav-link' %>
<%else%>
  <%= link_to "Signin", new_user_session_path %>
  <%= link_to "Create Account", new_user_registration_path %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeOnboardingPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">HR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active', 'aria-current': 'page' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Information
          </a>
        <ul class="dropdown-menu">
          <%# <li><%= link_to 'Add_Bus', buses_path, class: 'dropdown-item' %>
          <%# <li><%= link_to 'Add_route', routes_path, class: 'dropdown-item' %> 
        </ul>
        </li>
         <li class="nav-item">
          <%# <%= link_to 'Booking', bookings_path, class: 'nav-link active', 'aria-current': 'page' %>
        </li>
        </li>
         <li class="nav-item">
          <%# <%= link_to 'Bus', root_path, class: 'nav-link active', 'aria-current': 'page' %>
        </li>
        </li>
         <li class="nav-item">
          <%# <%= link_to 'Train', trains_path, class: 'nav-link active', 'aria-current': 'page' %>
        </li>
        </ul>
        <form class="d-flex" role="search">
      <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to "Logout", users_sign_out_path, data: { turbo_method: :delete }, class: 'nav-link' %>
          <% else %>
          <%= link_to " Login ", new_user_session_path, class: 'nav-link' %>
        <% end %> 
        </ul>
      </div>
    </nav>
  </header>

  </form>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.check_box :two_factor_enabled %>
  <%= f.label :two_factor_enabled, 'Enable Two-Factor Authentication' %>
  <%= f.submit 'Update' %>
<% end %>